# Generated by Django 5.0.7 on 2024-08-04 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_profile_father_alter_profile_mother_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date_of_death',
            field=models.DateField(blank=True, null=True),
        ),
    ]
