# Generated by Django 5.0.7 on 2024-08-04 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_profile_date_of_death'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(verbose_name='data de nascimento'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='date_of_death',
            field=models.DateField(blank=True, null=True, verbose_name='data de falecimento'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='father',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='father_children', to='profiles.profile', verbose_name='pai'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='nome'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='sobrenome'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mobile_number',
            field=models.CharField(max_length=20, null=True, verbose_name='celular'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mother',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mother_children', to='profiles.profile', verbose_name='mae'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='telefone'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='spouse',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='profiles.profile', verbose_name='casal'),
        ),
    ]
